
create table if not exists daily_logs (
  id bigint generated by default as identity primary key,
  log_date date unique not null,
  weight numeric(5,1),
  ai_comment text,
  updated_at timestamptz default now()
);

create table if not exists meal_logs (
  id bigint generated by default as identity primary key,
  log_date date not null,
  meal_type text not null check (meal_type in ('朝食','昼食','夕飯','夜食','間食')),
  meal_text text,
  vomited boolean not null default false,
  created_at timestamptz default now()
);

create table if not exists exercise_logs (
  id bigint generated by default as identity primary key,
  log_date date not null,
  exercise_type text not null check (exercise_type in ('腹筋','腹斜筋','スクワット','ジム','パーソナル')),
  memo text,
  created_at timestamptz default now()
);

create table if not exists muscle_soreness_logs (
  id bigint generated by default as identity primary key,
  log_date date not null,
  muscle_name text not null,
  created_at timestamptz default now()
);

create index if not exists idx_meal_date on meal_logs(log_date);
create index if not exists idx_exercise_date on exercise_logs(log_date);
create index if not exists idx_soreness_date on muscle_soreness_logs(log_date);
